name: Deploy to Private Server

on:
  push:
    branches: [ main ]  # 触发工作流的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 更新代码仓
          cd /root/workspace/convertflow
          git pull origin main
          
          # 后端部署
          cd backend
          pip install -r requirements.txt
          
          # 重启您的后端服务,例如:
          sudo systemctl restart convertflow_backend

          # 前端部署
          cd ../frontend
          pnpm install
          pnpm build