name: Deploy to Private Server

on:
  push:
    branches: [ main ]  # 触发工作流的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to private server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 进入项目目录
          cd /root/workspace/convertflow

          # 拉取最新代码
          git pull origin main

          # 更新后端依赖
          cd backend
          pip install -r requirements.txt
          
          # 重启后端服务
          # 根据您的实际情况修改这个命令
          sudo systemctl restart your-backend-service

          # 更新前端依赖并构建
          cd ../frontend
          pnpm install
          pnpm build